### ISSUE TITLE
安装成功，有一些疑问

### ISSUE THREAD

**Issue by wuyudi** [Zacharia2/SuperMemo18-ON-Wine#1]
我曾经折腾过 linux 上的安装。也“成功”了，但是 wine 模拟 win xp 时，中文会非常卡顿（winetricks 只提供了 ie8）。虚拟机使用也不太方便。
然后找到了这个项目，目前写了个 PKGBUILD 安装好了，发现中文编辑不卡了。看了眼 winecfg, 发现似乎是因为全用了原装的 ie 系列组件？

**Comment by Zacharia2** [comment]
> 我曾经折腾过 linux 上的安装。也“成功”了，但是 wine 模拟 win xp 时，中文会非常卡顿（winetricks 只提供了 ie8）。虚拟机使用也不太方便。 然后找到了这个项目，目前写了个 PKGBUILD 安装好了，发现中文编辑不卡了。看了眼 winecfg, 发现似乎是因为全用了原装的 ie 系列组件？

嗯，我之前是在知乎上看到唯一的一篇关于SuperMemo安装在Linux上的教程，也没说太明白，不过慢慢也看的产不多了，后来安装的时候发现需要的依赖软件下载不下来，于是手动下载放到特定目录下，之后就安装成功了。在后来发现了winetricks的SuperMemo配置安装项目，然后就到现在的基于它安装好的WINE环境打包好的容器环境。或许说不定你就是那个知乎的作者哦。如果是的话，那就太有缘分了。哈哈哈哈。

**Comment by wuyudi** [comment]
> > 我曾经折腾过 linux 上的安装。也 “成功” 了，但是 wine 模拟 win xp 时，中文会非常卡顿（winetricks 只提供了 ie8）。虚拟机使用也不太方便。 然后找到了这个项目，目前写了个 PKGBUILD 安装好了，发现中文编辑不卡了。看了眼 winecfg, 发现似乎是因为全用了原装的 ie 系列组件？
> 
> 嗯，我之前是在知乎上看到唯一的一篇关于 SuperMemo 安装在 Linux 上的教程，也没说太明白，不过慢慢也看的差不多了，后来安装的时候发现需要的依赖软件下载不下来，于是手动下载放到特定目录下，之后就安装成功了。在后来发现了 winetricks 的 SuperMemo 配置安装项目，然后就到现在的基于它安装好的 WINE 环境打包好的容器环境。或许说不定你就是那个知乎的作者哦。如果是的话，那就太有缘分了。哈哈哈哈。

当时也是因为 linux 安装这软件真的麻烦。甚至整理了一篇文章（没错就是你看到的那篇），然后因为受不了中文的速度，用虚拟机顶了一阵。现在看来不需要了。

https://honeysuckle-terrier-6c8.notion.site/Linux-supermemo18-4aba7bc9d74243f7986e8a5e03cbbe74

**Comment by wuyudi** [comment]
我参考某仓库完成了安装，写了教程。
参考教程有了这个仓库。
参考这个仓库有了 Arch 的包。
说没有天意我是不信的。🤣

**Comment by Zacharia2** [comment]
@wuyudi 发布新版deb安装包了，可以试试看。仓库也重构了目录结构。
