### ISSUE TITLE
创建软件包时出现错误

### ISSUE THREAD

**Issue by zhaoxian-afra** [Zacharia2/SuperMemo18-ON-Wine#16]
Arch Linux下：
错误：RPC 失败。curl 18 HTTP/2 stream 5 was not closed cleanly before end of the underlying connection
错误：预期仍然需要 7869 个字节的正文fetch-pack: unexpected disconnect while reading sideband packet
致命错误：过早的文件结束符（EOF）致命错误：fetch-pack：无效的 index-pack 输出==> 错误： 下载 SuperMemo18-ON-Wine git 仓库失败    正在放弃...

**Comment by Zacharia2** [comment]
@wuyudi

**Comment by Zacharia2** [comment]
@zhaoxian-afra 或许是网络链接问题，Github可能需要魔法访问。

**Comment by zhaoxian-afra** [comment]
> @zhaoxian-afra 或许是网络链接问题，Github可能需要魔法访问。

我是用了魔法之后的，唉

**Comment by Zacharia2** [comment]
@zhaoxian-afra 但这个情况好像就是网络问题。

**Comment by zhaoxian-afra** [comment]
> @zhaoxian-afra 但这个情况好像就是网络问题。

今天终于成功了，感谢！
