### ISSUE TITLE
软件包体系结构(i386)与本机系统体系结构(amd64)不符

### ISSUE THREAD

**Issue by Twist-ttt** [Zacharia2/SuperMemo18-ON-Wine#18]
'$ sudo dpkg -i SuperMemo18.05-lazy-winetricks.v1.4.0.1.deb '
'[sudo] twist 的密码：'
'dpkg: 处理归档 SuperMemo18.05-lazy-winetricks.v1.4.0.1.deb (--install)时出错： '
'软件包体系结构(i386)与本机系统体系结构(amd64)不符在处理时有错误发生： SuperMemo18.05-lazy-winetricks.v1.4.0.1.deb'

**Comment by Twist-ttt** [comment]
（刚开始学，还没会，见谅）

**Comment by Zacharia2** [comment]
@Twist-ttt 抱歉，这么晚才看到你的消息，这是因为软件架构与系统架构不兼容的问题，话说amd64不应该兼容32位软件吗？

**Comment by Zacharia2** [comment]
似乎这样可以解决问题：https://tieba.baidu.com/p/2057886463
