### ISSUE TITLE
箭头显示的问题

### ISSUE THREAD

**Issue by heisaari** [Zacharia2/SuperMemo18-ON-Wine#5]
安装方式是直接deb安装（SuperMemo18-Wine32-dpkg-3.deb）
自带教程里的 CTRL + 左右上箭头没有显示出来，字体的问题？
但执行cp -rf wine-fonts/* $HOME/.local/share/wineprefixes/SM18-Wine32/drive_c/windows/Fonts
返回：cp: cannot stat 'wine-fonts/*': No such file or directory
share目录下没找到wineprefixes目录

尝试卸载了deb，之后用
wget https://github.com/Zacharia2/SuperMemo18-ON-Wine/releases/download/v3/SuperMemo18-Wine32-dpkg-3.deb \
&& sudo apt install ./SuperMemo18-Wine32-dpkg-3.deb
命令重试，箭头还是没有显示出来

**Comment by Zacharia2** [comment]
可以方便截图看看嘛？

**Comment by Zacharia2** [comment]
SuperMemo18-Wine32-dpkg-3.deb的具体说明在这里，可以看一下：https://www.bilibili.com/read/cv16591644?spm_id_from=333.999.0.0

**Comment by heisaari** [comment]
> 可以方便截图看看嘛？
![s](https://user-images.githubusercontent.com/108096168/187604996-13c7f52c-f744-4951-a1ab-d2af98f91adb.png)

**Comment by Zacharia2** [comment]
这可能是缺少相应的字体吧，你可试着添加相关的字体到sm18-Wine32/drive_c/windows/font

**Comment by heisaari** [comment]
字体比较多不知如何确定，我直接手改了

**Comment by Zacharia2** [comment]
OK

**Comment by Zacharia2** [comment]
符号字体wingdings

**Comment by Zacharia2** [comment]
公式符号字体：symbol.ttf

**Comment by Zacharia2** [comment]
Segoe UI Emoji表情字体 、MT Extra、MS Reference Specialty

**Comment by Zacharia2** [comment]
可以直接重新输入符号文字。
