### ISSUE TITLE
希望增加或提供让supermemo默认在D盘的方法

### ISSUE THREAD

**Issue by heisaari** [Zacharia2/SuperMemo18-ON-Wine#6]
主要是之前的集合绿化在Win下的D盘了（图片、mp3），想在两系统无缝地拷贝切换用

**Comment by Zacharia2** [comment]
不太明白你的意思，如果是Linux系统是不存在C盘D盘的。不过有种方法可以，如果你是虚拟机，你可以使用文件共享功能链接到SuperMemo18-ON-Wine的systems 和 SuperMemo资料库 目录，如果不是虚拟机，你也可以使用网络共享等这样的web服务。

https://www.bilibili.com/read/cv16591644?spm_id_from=333.999.0.0

**Comment by heisaari** [comment]
下载的卡包可以放在这个目录:/mnt/SuperMemo卡包 ,该目录链接 C:\\SuperMemo/systems，打开它点击SuperMemo18.desktop启动supermemo，在sm中打开卡包。

 需要被sm18访问到的文件放在这个目录: /mnt/SuperMemo资料库，该目录链接 C:\\SuperMemo/SuperMemo资料库，导入资料时选择C:\\SuperMemo/SuperMemo资料库,目录即可。 作者：ZWizard https://www.bilibili.com/read/cv16591644?spm_id_from=333.999.0.0 出处：bilibili
___________________________
我的意思是，windows下sm是分盘符的，我的资料里的图片音频链接都指向了D盘（即把它的目录在win下移动到其他盘符会报错）；看上面的说明是要放在 C:\\SuperMemo/systems的，直接拷贝过去应该是不行的吧

**Comment by Zacharia2** [comment]
你可以增加一个盘符，链接到Linux任意一个文件夹，你可以使用winecfg命令配置

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/187606319-28dede98-9319-4532-86f5-94531175e713.png)

在驱动器选项卡修改

**Comment by heisaari** [comment]
谢谢指导，winecfg提示命令未找到，开始菜单里有一个wine-sm18.05-winecfg可以运行，在它的Drive标签里添加了一个D盘，指向了home目录下的一个子文件夹
但是运行sm后找开菜单里的盘符下拉列表里并没有出现D盘或其他盘，是我哪里做错了吗

**Comment by Zacharia2** [comment]
嗯（(ᇂ_ᇂ|||)，这真的很尴尬，看你的描述似乎没有做错，但是我手边现在没有Linux系统，暂时无法为您解答这个问题。

**Comment by Zacharia2** [comment]
图里正在更新wine配置，这是随便找到一个图，不用在意，只是为了说明怎么增加驱动器，按理说增加驱动器之后应该就可以了，但是现在却不行，嗯值得好好想想这个问题。

**Comment by heisaari** [comment]
好的谢谢

**Comment by heisaari** [comment]
尝试运行env WINEARCH=win32 WINEPREFIX="/opt/SM18-Wine32/" sm-wine winecfg命令，有报错，不知对解决此问题有无帮助
`0025:err:module:load_builtin_dll failed to load .so lib for builtin L"winebus.sys": libudev.so.0: cannot open shared object file: No such file or directory
0025:err:winedevice:async_create_driver failed to create driver L"winebus": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"winebus" failed to start: 31
`

**Comment by heisaari** [comment]
今天偶然找到了解决办法！：
引入一个音频，因为之前的包默认是在D盘的，出来的对话框会问你要不要创建，yes即可
之后就成了

**Comment by heisaari** [comment]
还是想简单了，导入那里能出现D盘，但直接从文件--打开那里还是看不到

**Comment by Zacharia2** [comment]
已解决

**Comment by Zacharia2** [comment]
已发布新版构建deb安装包

**Comment by heisaari** [comment]
许久未来，今天上来一下居然解决了已经，THX!!

**Comment by heisaari** [comment]
运行了一下，突然就报：
Cannot open player device
初始化 MCI 时出现问题。请尝试重新启动 Windows。
反复重新进入依旧

**Comment by Zacharia2** [comment]
@heisaari 查看  https://github.com/Zacharia2/SuperMemo18-ON-Wine/issues/9
