### ISSUE TITLE
cannot open player device

### ISSUE THREAD

**Issue by wuyudi** [Zacharia2/SuperMemo18-ON-Wine#9]
测试了下，别的都正常，音频会出问题。

![image](https://user-images.githubusercontent.com/30024051/211201459-95646062-5acc-49c2-8974-dd6e8cec44fa.png)

对应的报错 https://supermemopedia.com/wiki/Cannot_open_player_device

这个报错会把整个 wine 卡死

~~放个 issue 供后人查阅吧~~

**Comment by Zacharia2** [comment]
MCI 可能是缺少编解码器吧。
你看看闹钟可以响嘛？在窗口右下角。

**Comment by Zacharia2** [comment]
安装解码器K-Lite Codec Pack或许可以解决MCI的问题。

**Comment by wuyudi** [comment]
> 你看看闹钟可以响嘛？在窗口右下角。

试了，可以。

**Comment by Zacharia2** [comment]
嗯，那可能就是你的系统缺少解码器的缘故了

**Comment by Zacharia2** [comment]
可以试试安装Linux解码器软件，再不行就安装上文中的解码器软件道wine容器中。

**Comment by wuyudi** [comment]
bug 摸清楚了。

专业模式工作正常，但是切到基础模式

![image](https://user-images.githubusercontent.com/30024051/211539758-d6316509-7f69-4295-9a8f-8ada086d9eb7.png)

先点击 示例2 再点击 极速音频制卡注意事项 就卡死。

**Comment by wuyudi** [comment]
~~那就只用专业模式吧，bug 解决了。~~
